# Generated by Django 5.1.4 on 2025-01-10 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to="image/lesson", verbose_name="Превью урока"),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
                ("video_url", models.URLField(blank=True, max_length=400, null=True, verbose_name="Ссылка на видео")),
            ],
            options={
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to="image/course", verbose_name="Превью курса"),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lessons",
                        to="materials.lesson",
                        verbose_name="Уроки",
                    ),
                ),
            ],
            options={
                "verbose_name": "курс",
                "verbose_name_plural": "курсы",
            },
        ),
    ]
